# Xamarin.Android

trigger:
- main

variables:
- group: 'variables'

jobs:
  - job: 'BuildAndroid'
    pool:
      vmImage: 'windows-2022'
      
    variables:
      buildConfiguration: 'Release'
      outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
      - task: android-manifest-version@1
        inputs:
          sourcePath: 'ep.Android/Properties/AndroidManifest.xml'
          versionCodeOption: 'buildid'
          versionCode: '$(Build.BuildId)'
          printFile: true
      - task: XamarinAndroid@1
        inputs:
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(build.binariesDirectory)'
          configuration: '$(buildConfiguration)'
          msbuildVersionOption: latest
      
      # - task: DownloadSecureFile@1
      #   name: keystore
      #   inputs:
      #     secureFile: '$(KeyStore-FileName)'
          
      - task: AndroidSigning@3
        inputs:
          apkFiles: '**/*.apk'
          apksign: true
          zipalign: true
          apksignerKeystoreFile: '$(KeyStore-FileName)'
          apksignerKeyPassword: '$(KeyStore-Password)'
          apksignerKeystoreAlias: '$(KeyStore-Alias)'
          apksignerKeystorePassword: '$(KeyStore-Password)'
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'ep.Android\obj\Release\110\android\bin\com.companyname.testmobile.apk'
          artifactName: 'AndroidApk'

      # - task: CopyFiles@2
      #   inputs:
      #     Contents: '**/*.apk'
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
      #     OverWrite: true
      #     flattenFolders: true
          
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'MyAwesomeApp-$(Build.BuildNumber)'
      #     publishLocation: Container

      # - task: XamarinAndroid@1
      #   inputs:
      #     projectFile: '**/*droid*.csproj'
      #     outputDirectory: '$(Build.BinariesDirectory)'
      #     configuration: '$(BuildConfiguration)'
      #     clean: true
      #     msbuildVersionOption: latest
      #     msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME_11_X64)/" 
      #                        /p:AndroidPackageFormat=aab 
      #                        /t:SignAndroidPackage 
      #                        /p:AndroidNdkDirectory="$(androidNdkPath)" 
      #                        /p:AndroidKeyStore="True" 
      #                        /p:AndroidSigningKeyStore="$(keystore.secureFilePath)" 
      #                        /p:AndroidSigningKeyPass="$(KeyStore-Password)" 
      #                        /p:AndroidSigningKeyAlias="$(KeyStore-Alias)" 
      #                        /p:AndroidSigningStorePass="$(KeyStore-Password)"'

      # - task: CopyFiles@2
      #   inputs:
      #     Contents: '**/*.aab'
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
      #     OverWrite: true
      #     flattenFolders: true

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'MyAwesomeApp-$(Build.BuildNumber)'
      #     publishLocation: Container
  - job: AndroidBeta
    displayName: "Release Android Beta"
    dependsOn: [BuildAndroid]
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: AndroidApk
      - task: AppCenterDistribute@3
        inputs:
          serverEndpoint: 'App Center'
          appSlug: 'EP-Mobile/EP'
          appFile: '$(Pipeline.Workspace)/com.companyname.testmobile.apk'
          symbolsOption: 'Android'
          releaseNotesOption: 'file'
          releaseNotesFile: 'releasenotes.txt'
          destinationType: 'groups'
          distributionGroupId: '0d01adb6-b2fb-4385-a9fc-2f2f7ca74d17'